import type { Metadata } from "next";
import { Montserrat, Creepster } from "next/font/google";
import "./globals.scss";
import ApolloProvider from "@/providers/apolloProvider";
import { FavoritesProvider } from "@/context/favoritesContext";

const MontserratFont = Montserrat({
  variable: "--font-Montserrat",
  weight: ["400", "700", "800"],
  subsets: ["latin"],
});

const CreepsterFont = Creepster({
  variable: "--font-Creepster",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${MontserratFont.variable} ${CreepsterFont.variable}`}>
        <FavoritesProvider>
          <ApolloProvider>{children}</ApolloProvider>
        </FavoritesProvider>
      </body>
    </html>
  );
}
